version: '3'
services:
  web:
    build: .
    command: python ./django_web_app/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app/db
  # vue:
  #   image: node:20
  #   working_dir: /var/www/html/app/
  #   command: npm run dev
  #   entrypoint: /bin/bash
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./vue/:/var/www/html/app
  #   tty: true
