version: '3'
services:
  web:
    build: .
    command: python ./django_web_app/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app/db
      - ./static:/static
      - ./templates:/templates
    depends_on:
      - frontend
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./static:/static
      - ./templates:/templates

